version: "3"

services:
  node:
    image: eosio/eos-dev:v1.2.5
    command: nodeos --data-dir /mnt/dev/data --config-dir /mnt/dev/data --contracts-console
    hostname: node
    container_name: eosdev_node
    ports:
      - "8888:8888"
      - "9876:9876"
    volumes:
      - ./node/data:/mnt/dev/data
      - ./node/config.ini:/mnt/dev/data/config.ini


  wallet:
    image: eosio/eos-dev:v1.2.5
    command: /opt/eosio/bin/keosd --data-dir /opt/eosio/bin/data-dir
    hostname: wallet
    container_name: eosdev_wallet
    links:
      - node
    volumes:
      - ./wallet:/opt/eosio/bin/data-dir
      - ./work:/work

      #- ./config.ini:/opt/eosio/bin/data-dir/config.ini
